"""Adapted from originals/Basic LM with Sentence Generation.py.

Trigram language model (P(w3 | w1, w2)) built from the corpus sentences with
None-padding on both sides.  Sentences are generated by weighted random
sampling from a fixed starting phrase until the model emits two Nones.

Usage: python basic_lm.py [seed]
"""
from nltk import trigrams
from collections import defaultdict
import random
import sys

from corpus_config import corpus, CORPUS_NAME

if len(sys.argv) > 1:
    random.seed(int(sys.argv[1]))

test_sentence = corpus.sents()[0]
print(f"{CORPUS_NAME} corpus loaded successfully ({len(corpus.sents())} sentences)")

# Create a placeholder for the model
model = defaultdict(lambda: defaultdict(lambda: 0))

# Count frequency of co-occurrence
for sentence in corpus.sents():
    for w1, w2, w3 in trigrams(sentence, pad_right=True, pad_left=True):
        model[(w1, w2)][w3] += 1

# Transform the counts to probabilities
for w1_w2 in model:
    total_count = float(sum(model[w1_w2].values()))
    for w3 in model[w1_w2]:
        model[w1_w2][w3] /= total_count

# Print model example.  The original does dict(model["part","of","the"]), which
# looks up a 3-tuple in a dict keyed by 2-tuples and therefore always prints {}.
# Show the intended context ("of", "the") instead, trimmed to its 10 likeliest
# continuations because the full distribution has hundreds of entries.
context = ("of", "the")
top = sorted(model[context].items(), key=lambda kv: -kv[1])[:10]
print(f"P(w | {context}) top 10 of {len(model[context])}: "
      + ", ".join(f"{w}={p:.3f}" for w, p in top))

# Function to generate sentences
def generate_sentence(starting_words):
    text = starting_words
    sentence_finished = False

    while not sentence_finished:
        r = random.random()
        accumulator = 0.0

        for word in model[tuple(text[-2:])].keys():
            accumulator += model[tuple(text[-2:])][word]
            if accumulator >= r:
                text.append(word)
                break

        if text[-2:] == [None, None]:
            sentence_finished = True

    return ' '.join([t for t in text if t])

# Generate 20 sentences
for _ in range(20):
    print(generate_sentence(["part", "of", "the"]))
